In [1]:
#Importacion de numpy
import numpy as np

In [2]:
#CREACIÓN DE ARREGLOS----------------------

#Array de números aleatorios desde cero
arrayAleatorios = np.random.rand(20)
arrayAleatorios

array([0.63924762, 0.11530281, 0.28763809, 0.59124191, 0.37338403,
       0.5749471 , 0.9363178 , 0.14993327, 0.8867021 , 0.70607145,
       0.52424826, 0.22651651, 0.57594877, 0.83889814, 0.91760257,
       0.21400389, 0.97275232, 0.36590432, 0.06926018, 0.11285099])

In [3]:
#Array de números aleatorios enteros desde cero
arrayAleatoriosEnteros = np.random.randint(20, size=20)
arrayAleatoriosEnteros

array([18,  2, 11,  8, 16,  0,  2, 13,  5, 10, 16, 15, 10, 15,  2,  2,  2,
       13,  8,  5])

In [7]:
#Array lleno de 0  
arrayCeros = np.zeros(10)
arrayCeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
#Array lleno de 1
arrayUnos = np.ones(10)
arrayUnos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
#Array de una sucesión de números

#Inicia por defecto en 0 y con incremento en 1
#siendo 10 el valor final
array_CeroDiez = np.arange(10)
array_CeroDiez

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#Inicia en 0, hasta 20, con incremento en 2
array_pares = np.arange(0,20,2)
array_pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
#Inicia en 1, hasta 21, con incremento en 2
array_impares = np.arange(1,21,2)
array_impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [13]:
#Cambiar la dimension de arreglos ya creados
#Cantidad de filas 2, Cantidad de columnas 5
array_pares_reshaped = array_pares.reshape(2,5)
array_pares_reshaped

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [29]:
#OPERACIONES ENTRE ARREGLOS-----------------

#Sumar, restar, multiplicar, dividir, elevar, aplicar seno cada elemento de un array
array_pares+1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [30]:
array_impares-1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
array_CeroDiez/10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [32]:
arrayUnos*10

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [33]:
array_pares**2

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324])

In [34]:
np.sin(array_impares)

array([ 0.84147098,  0.14112001, -0.95892427,  0.6569866 ,  0.41211849,
       -0.99999021,  0.42016704,  0.65028784, -0.96139749,  0.14987721])

In [20]:
#Sumar, restar, multiplicar y dividir arrays entre arrays
array_pares + array_pares

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [21]:
array_impares - array_impares

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
array_CeroDiez * array_CeroDiez

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [23]:
arrayUnos / arrayUnos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
array_pares @ array_impares

1230

In [25]:
array_pares.dot(array_impares)

1230

In [26]:
#Métodos estadísticos dentro un array
#Suma de los valores dentro del array
array_CeroDiez.sum()

45

In [27]:
#Promedio de los valores dentro del array
array_pares.mean()

9.0

In [35]:
#Varianza de los valores dentro del array
array_impares.var()

33.0

In [36]:
#ORDEN Y SELECCIÓN EN ARREGLOS--------------

#Ordenar arrays
#Ordenar de mayor a menor
-np.sort(-arrayAleatoriosEnteros)

array([18, 16, 16, 15, 15, 13, 13, 11, 10, 10,  8,  8,  5,  5,  2,  2,  2,
        2,  2,  0])

In [37]:
#Ordenar de menor a mayor
np.sort(arrayAleatoriosEnteros)

array([ 0,  2,  2,  2,  2,  2,  5,  5,  8,  8, 10, 10, 11, 13, 13, 15, 15,
       16, 16, 18])

In [39]:
#Obtener primer elemento
#Tener en cuenta la dimensión del array
array_CeroDiez[0]

0

In [40]:
#Obtener ultimo elemento
#Tener en cuenta la dimensión del array
array_pares_reshaped[1,4]

18

In [41]:
#Obtener cierta fila
array_pares_reshaped[1,:]

array([10, 12, 14, 16, 18])

In [42]:
#Obtener cierta columna
array_pares_reshaped[:,1]

array([ 2, 12])

In [43]:
#Validar condicion 
#números menores a 20 de un array aleatorio
arrayAleatoriosEnteros<10

array([False,  True, False,  True, False,  True,  True, False,  True,
       False, False, False, False, False,  True,  True,  True, False,
        True,  True])

In [44]:
#Obtener los valores que cumplen cierta condición
#Obtener números mayores a 10 de un array aleatorio
arrayAleatoriosEnteros[arrayAleatoriosEnteros>10]

array([18, 11, 16, 13, 16, 15, 15, 13])